### ISSUE TITLE
node_modules/injection-js/util/decorators.d.ts(11,5): error TS2411: Property 'extends' of type 'Type<any> | undefined' is not assignable to string index type 'Function | any[] | Type<any>'.

### ISSUE THREAD

**Issue by jamieathans** [mgechev/injection-js#11]
Using this library, I get a typescript error as specified in the title.

Typescript: v2.3.2
injection-js: v2.0.1

My work-around is to enable `"skipLibCheck": true` in the tsconfig.json.

**Comment by mgechev** [comment]
I haven't updated to Angular 4.1 which is compatible with `strictNullCheck`. I'll do that today.

**Comment by mgechev** [comment]
@jamieathans done, you can try `injection-js@2.1.0`. Let me know if you face any issues.
