### ISSUE TITLE
Angular like Modules

### ISSUE THREAD

**Issue by paulhobbel** [mgechev/injection-js#12]
Hello,
I know this is not supposed to be a part of a di, but still going to ask it. I've been researching the way Angular handles the @NgModule decorator, but I can't figure it out. Is it possible to build something similar with injection-js?

**Comment by mgechev** [comment]
Yes, this doesn't belong to. `@NgModule` decorator is only partially related to the DI, its main purpose is providing a context for the compiler.

In fact, the providers you pass to a `@NgModule` and its imports are being merged and passed to the factory method of `ReflectiveInjector`.
