### ISSUE TITLE
Support constructor overrides using decorators

### ISSUE THREAD

**Issue by lizardruss** [mgechev/injection-js#14]
Hi!

Thank you so much for making this available outside of Angular.

I'm attempting to create a class decorator that sets configuration values based on property decorators, but it seems that overriding the constructor with a class decorator makes injection-js stop working. Here's an example of my code:

```typescript
export function Configurable() {
  return <T extends {new(...args: any[]): {}}>(constructor: T): T => {
    return class extends constructor {
      constructor(...args: any[]) {
        super(...args);
        console.log('HERE!');
      }
    };
  };
}
```

When I use this along with the `@Injectable()` decorator, `'HERE!` is logged to the console, but dependencies are not injected.

Any ideas on how to get both to work?

**Comment by mgechev** [comment]
Since this is complete extraction of the DI from `@angular/core`, this issue should be reported there.
