### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by MickL** [mgechev/injection-js#18]
This project looks fantastic. Coming from the Angular-world I'm not 100% sure how to use this module looking at the documentation:

In Angular I am used to declare the providers within a module or component. That way i have the possbility to declare singletons for the whole app or one instance per module or per component. 

Questions:
- Where to register providers for global/scoped usage?
- How to inject them?
- Do they work across different files?

E.g. i want to use `HttpClient` from Angular as one instance globally. Also i want to create one instances of my service `@Injectable() GameStoreService` for a each `class Game { }` or each element of an array.

**Comment by MickL** [comment]
Found a very nice documentation with examples within the code at node_modules/injection-js/reflective_injector.d.ts. This could nearly be transfered as it is to the readme.

There are more functions than the README tells. Reading all makes understanding it alot better.

This is my final code:

```
let games = [
   // ... 
];

// This gets created once for all
const injector = ReflectiveInjector.resolveAndCreate([
    ...HTTP_CLIENT_PROVIDERS, // Using node-angular-http-client to get Angular HttpClient
]);

// This creates a provider, but no Class will be instantiated
export const storeProvider = ReflectiveInjector.resolve([GameStoreService])[0];

games.forEach(game => {
   // This creates a new instance for each game
   game.store = injector.instantiateResolved(storeProvider);
});
```

**Comment by mgechev** [comment]
@MickL would be great if you open a PR with your suggestion!

**Comment by mgechev** [comment]
Closing it due to lack of activity.

**Comment by MickL** [comment]
In my opinion you should leave this open. Using this Module is farly different from registering Services in Angular.

The project is well documented within code, cant you just port it and give some more examples? I dont habe the time sorry.
