### ISSUE TITLE
ReflectiveInjector vs StaticInjector

### ISSUE THREAD

**Issue by srdone** [mgechev/injection-js#20]
I noticed that as of Angular 5, ReflectiveInjector is deprecated in Angular. What are your plans for this extraction of that code? Will you be updating to the StaticInjector implementation or just maintaining ReflectiveInjector separately here in injection-js going forward?

**Comment by mgechev** [comment]
I will write a blog post about this.

No, injection-js won't move to `StaticInjector` because we don't need to introduce a compilation step.

In fact, injection-js is the migration option for all the non-Angular projects in the wild using Angular's DI.

**Comment by srdone** [comment]
Thank you!
