### ISSUE TITLE
Factory service with async

### ISSUE THREAD

**Issue by zender** [mgechev/injection-js#26]
Question: Is it possible to register service like this (useful for db connections and etc...):

```typescript
{
      provide: SomeService,
      useFactory: async () => {
        const conn = await createConnection({});
        return new SomeService(conn);
      },
      deps: []
}
```

and to get resolved service from the injector:
```typescript
// should be instance of already resolved service not a promise
injector.get(SomeService);
```

**Comment by mgechev** [comment]
Unfortunately, it's not. All the factories should be sync.

**Comment by menosprezzi** [comment]
Hi!
It's possible use the APP_INITIALIZER injection token?
