### ISSUE TITLE
Constructor of @Injectable class triggered multiple times

### ISSUE THREAD

**Issue by nxddsnc** [mgechev/injection-js#28]
I am using injection-js to implement ioc without angular. It worked fine. But the constructor of the injected class was triggered multiple times.  Here the code
```ts
    // var bindings = ReflectiveInjector.resolve([DataService]);
    // const injector = ReflectiveInjector.fromResolvedProviders(bindings);
    const injector = ReflectiveInjector.resolveAndCreate([DataService]);
    this.dataService = injector.get(DataService)
```
Neither fromResolvedProviders nor resolveAndCreate works.  Am I using it the wrong way or this library does not intend to implement singleton?

**Comment by mgechev** [comment]
Would you share the declarations of the services as well?

**Comment by nxddsnc** [comment]
Sorry. Seems that I did not describe my issue correctly. I injected the 'DataService' to several Classes.

**Comment by mgechev** [comment]
Would you provide the entire example so I can reproduce the issue?

**Comment by nxddsnc** [comment]
The entire project is too large. So I create a test example here: https://github.com/nxddsnc/injectorTest. 
After building this with webpack, I use it like:
`
let b = new ServiceB();
let c = new ServiceC();
`
in the constructors of the class ServiceB and ServiceC, I use this to get the ServiceA:
`
const injector = ReflectiveInjector.resolveAndCreate([ServiceA]);
let serviceA = injector.get(ServiceA);
`
And there's two logs says "service A constructed";

**Comment by mgechev** [comment]
@nxddsnc you should not create an instance of the `ReflectiveInjector` inside of the classes' constructors. You should turn this code:

```ts
import { Injectable, ReflectiveInjector } from 'injection-js';

@Injectable()
export class ServiceA {
  constructor() {
    console.log('service A constructed');
  }
}

@Injectable()
export class ServiceB {
  constructor() {
    const injector = ReflectiveInjector.resolveAndCreate([ServiceA]);
    let serviceA = injector.get(ServiceA);
  }
}
```

Into:

```ts
import 'reflect-metadata';
import { Injectable, ReflectiveInjector } from 'injection-js';

export class ServiceA {
  constructor() {
    console.log('service A constructed');
  }
}

@Injectable()
export class ServiceB {
  constructor(private serviceA: ServiceA) {}
}

const injector = ReflectiveInjector.resolveAndCreate([ServiceA, ServiceB]);
injector.get(ServiceB);
```

Notice the following:

- You need `reflect-metadata`.
- You need to set `emitDecoratorMetadata` flag in `tsconfig.json` to `true.
- `ServiceB` is delegating the instantiation of `ServiceA` to the `ReflectiveInjector`. This way `ServiceB` is not coupled with a specific abstraction (i.e. `ReflectiveInjector` can pass a subclass of `ServiceA`), neither with the process of instantiation of `ServiceA`.

**Comment by nxddsnc** [comment]
Understood. Thank you very much!
