### ISSUE TITLE
FirstHelper does not exist in type Provider[] using resolveAndCreate?

### ISSUE THREAD

**Issue by iangregsondev** [mgechev/injection-js#3]
Hi,

I am having a few issues, I am getting the following error

> Error:(54, 5) TS2345:Argument of type '{ FirstHelper: typeof FirstHelper; SecondHelper: typeof SecondHelper; }' is not assignable to parameter of type 'Provider[]'.
>   Object literal may only specify known properties, and 'FirstHelper' does not exist in type 'Provider[]'.

Also running it in the browser gives a second error, but i presume its because of the first one above

```
Uncaught TypeError: providers.forEach is not a function
    at _normalizeProviders (injection.bundle.js:1333)
    at resolveReflectiveProviders (injection.bundle.js:1292)
    at Function.ReflectiveInjector.resolve (injection.bundle.js:1764)
    at Function.ReflectiveInjector.resolveAndCreate (injection.bundle.js:1794)
    at Object.<anonymous> (Game.ts:53)
    at __webpack_require__ (bootstrap 1bf5f5c…:19)
    at Object.<anonymous> (bootstrap 1bf5f5c…:39)
    at __webpack_require__ (bootstrap 1bf5f5c…:19)
    at bootstrap 1bf5f5c…:39
    at bootstrap 1bf5f5c…:39
```

I have 2 clases, FirstHelper and SecondHelper, I wish to inject SecondHelper into First Helper.

I hope someone can help ?

I am basically doing the following

```
import "reflect-metadata";
import { ReflectiveInjector, Injectable } from 'injection-js';

import {FirstHelper} from "./infrastructure/helpers/FirstHelper";
import {SecondHelper} from "./infrastructure/helpers/SecondHelper";

const injector = ReflectiveInjector.resolveAndCreate({
    FirstHelper,
    SecondHelper
});
```

which is what is giving the provider error, I am placing my 2 classes below to demonstrate what I am doing.

First Helper is here 

```
import "reflect-metadata";
import {Injectable} from "injection-js";
import {SecondHelper} from "./SecondHelper";

@Injectable()
export class FirstHelper  {
    constructor(private secondHelper: SecondHelper) {
        debugger;
    }
    public print() {
        console.log("I am FirstHelper");
    }
}
```

and Second Helper is here

```
import "reflect-metadata";
import {Injectable} from "injection-js";
@Injectable()
export class SecondHelper  {

    public print() {
        console.log("I am SecondHelper");
    }
}
```

**Comment by iangregsondev** [comment]
Emm, So i noticed that the example on the front page was passing in an object but it needs to be an array :-) 

Now it seems to work.

**Comment by iangregsondev** [comment]
Maybe the document on the main screen needs updating ?

**Comment by mgechev** [comment]
Yes, incorrect example. It should be:

```ts
const injector = ReflectiveInjector.resolveAndCreate([
    FirstHelper,
    SecondHelper
]);
```
