### ISSUE TITLE
InjectionToken as token for provider doesn't work

### ISSUE THREAD

**Issue by qetr1ck-op** [mgechev/injection-js#35]
Arrange:
```ts
class Http { }

@Injectable()
class Service {
  constructor(
    private http: Http,
    @Inject(CONFIG_TOKEN) private config: Config // this cause the resolve error (see bellow)
  ) { }
}

interface Config {
  api: string
}
const config: Config = {
  api: 'api/v1'
}

const CONFIG_TOKEN = new InjectionToken<Config>('CONFIG_TOKEN')
```

Declare the providers:
```ts
const injector = ReflectiveInjector.resolveAndCreate([Service, Http, {
  provide: CONFIG_TOKEN, useValue: config
}]);
```

Consume:
```ts
injector.get(Service)
```

An error:
```
Error: Cannot resolve all parameters for 'Service'(Http, @Inject). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Service' is decorated with Injectable.
```

Demo: https://stackblitz.com/edit/typescript-iascmw

Details:
Seems that InjectionToken, OpaqueToken, native Symbols don't work as declaring keys for providers.
With strings, everything works as expected.

**Comment by qetr1ck-op** [comment]
And right after I found the bottleneck =) 
For me it wasn't obvious but, that:
```ts
const CONFIG_TOKEN = new InjectionToken('CONFIG_TOKEN')
```
should be declared and evaluated before the line of consuming DI:
```ts
@Inject(CONFIG_TOKEN) private config: Config
```
I suppose because of ts compiling phase. Correct me if I'm wrong.

And by the way. You did a tremendous job of extracting NG DI Framework and provide it for the community 🚀

**Comment by mgechev** [comment]
Thanks for the kind words and for sharing your findings! :)
