### ISSUE TITLE
Basic typescript example does not work in Create React App with typescript

### ISSUE THREAD

**Issue by renatoruk** [mgechev/injection-js#36]
Hello and thanks for the awesome library! I'm already using it through [rea-di](https://github.com/Hotell/rea-di), but currently I am stuck with some weird errors so maybe you can give a hint.

I've set up an [example repo](https://github.com/renatoruk/injection-js-cra) to better illustrate the issue.

Basically, doing a type annotation in a class constructor and setting the Injectable() decorator on the class somehow is not enough for the provider registration. This is [code that does not work](https://github.com/renatoruk/injection-js-cra/blob/master/src/non-working-example.ts).
 The error I'm getting is: 
`index.js:1375 Error: Cannot resolve all parameters for 'Service'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Service' is decorated with Injectable.` 

I've imported the reflection polyfill (@abraham/reflection), but also tried with reflect-metadata and the error persists. Also, tsconfig has experimentalDecorators and emitDecoratorMetadata set to true.

Somehow, the [ES6 version](https://github.com/renatoruk/injection-js-cra/blob/master/src/working-example.ts) of the code does work in ts environment. But then the registration is manual which is not ideal.

Any idea what can be the case? Can you maybe provide a basic typescript example set up that works?

**Comment by mgechev** [comment]
Thanks for giving the library a try! Would you provide a minimal example where I can reproduce the issue?

**Comment by renatoruk** [comment]
Sure, already did! 
- https://github.com/renatoruk/injection-js-cra
This is the code snippet of interest (that does not work): https://github.com/renatoruk/injection-js-cra/blob/master/src/non-working-example.ts

**Comment by mgechev** [comment]
Doesn't look like a problem in `injection-js`. Seems like the TypeScript compiler does not generate metadata although you've specified the flags.

This is what the output of the compilation is:

```js
"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var injection_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! injection-js */ "./node_modules/injection-js/index.js");
var _dec, _class, _dec2, _class2;


let Http = (_dec = Object(injection_js__WEBPACK_IMPORTED_MODULE_0__["Injectable"])(), _dec(_class = class Http {}) || _class); // tslint:disable-next-line:max-classes-per-file

let Service = (_dec2 = Object(injection_js__WEBPACK_IMPORTED_MODULE_0__["Injectable"])(), _dec2(_class2 = class Service {
  constructor(http) {
    this.http = http;
  }

}) || _class2);

try {
  const injector = injection_js__WEBPACK_IMPORTED_MODULE_0__["ReflectiveInjector"].resolveAndCreate([Http, Service]);
  console.log(injector.get(Service));
} catch (e) {
  console.error(e);
}
```

Looks like to use `emitDecoratorMetadata` you'd need the following Babel plugin `babel-plugin-transform-typescript-metadata`. On some reason CRA does not compile TypeScript with the TypeScript compiler, but delegates it to Babel.

**Comment by renatoruk** [comment]
Thank you for taking the time to check this. I did not realize that babel will not transpile this as no warning was given. Now reading the babel docs I can see the [caveat](https://babeljs.io/docs/en/babel-plugin-transform-typescript#typescript-compiler-options) that you've mentioned. 🤦‍♂️

My apologies for overlooking this. I really thought I may have misconfigured something. Now I'm looking forward to implementing injection-js completely. 👷‍♂️ Thanks again!

**Comment by mgechev** [comment]
No worries, it's not obvious where the issue is coming from.
