### ISSUE TITLE
Providers option

### ISSUE THREAD

**Issue by resynth1943** [mgechev/injection-js#39]
Is there an expressive and easy way to declare the providers of an `Injectable` *inside* that class? What would be the alternative of this in your library?

```ts
@Injectable({ 
  providers: ...
});
```

Many thanks. I await your reply.

**Comment by mgechev** [comment]
No, the providers are declared inside the injector. The services must depend only on abstractions, not specific implementations.

**Comment by resynth1943** [comment]
I asked the above because I have a component that has a parameter injected, using an `InjectionToken`. Let's call it `CAR_OPTIONS`. The global `CAR_OPTIONS` declared inside the injector is `{ hasEngine: true }`.

I could not find a way to make an injectable have it's *own* instance of `Car` with `CAR_OPTIONS` set to `{ hasEngine: true }`. Perhaps my question missed this.

**Comment by mgechev** [comment]
I'd recommend you going through the [docs](https://v4.angular.io/guide/dependency-injection) website to get a better understanding of how everything works together.

**Comment by resynth1943** [comment]
I saw the note. 
```html
<!-- TODO: Add a link to the section of the user guide talking about hierarchical injection. -->
```
This is precisely the part I'm getting stuck on. Please note that I've *read* the documentation before this (and that specific page). I understand how *Angular* does it, but not how this library does it.

**Comment by mgechev** [comment]
Here's the section which talks about [hierarchical injectors](https://v4.angular.io/guide/hierarchical-dependency-injection). The injector determines the scope of the declared providers; you can use the hierarchy to configure visibility. For further reference, I'd recommend you reviewing the guide again to make sure the pieces fit well together.
