### ISSUE TITLE
Singleton vs Instances ?

### ISSUE THREAD

**Issue by iangregsondev** [mgechev/injection-js#4]
Hi,

i am a little lost with if these are Singletons or new instances that are being injected. I am using the following example

```
const injector = ReflectiveInjector.resolveAndCreate([
    FirstHelper,
    SecondHelper,
    Game
]);
```

If they are actually instances then how do we force a singleton to be injected ? And if these are singletons or can we ensure that a new instance is injected each time ?

Does anyone have some examples ?

I am using typescript if that makes a difference.

Thanks

**Comment by iangregsondev** [comment]
Also this also begs the question that I have some singletons I created manually with a private constructor and a static getInstance method which returns me a singleton. How do I register an already created instance with the injector.

resolveAndCreate - seems to create the instance before registering it.

What if I have an already created instance that I wish to register with the DI container.

Can you mix and match and register already created instances and using resolveAndCreate for the system to create the instances.

Any ideas ?

Thanks

**Comment by mgechev** [comment]
Hey @appsolutegeek, you can follow the [Angular's documentation](https://angular.io/docs/ts/latest/guide/dependency-injection.html) or [thoughtram's blog post](https://blog.thoughtram.io/angular/2015/05/18/dependency-injection-in-angular-2.html).

In general:

```ts
const injector = ReflectiveInjector.resolveAndCreate([
  Http,
  Service
]);

injector.get(Http) === injector.get(Http) // true
```

The already existing instance can be registered with:

```ts
class Singleton ( ... }

const injector = ReflectiveInjector.resolveAndCreate([
  { provide: Singleton, useValue: Singleton.getInstance() }
]);
```

**Comment by wbhob** [comment]
Is `Singleton` an injectable class in this instance? I'm getting the error that `getInstance` is not a function.
