### ISSUE TITLE
dynamically resolve all dependencies?

### ISSUE THREAD

**Issue by seiyria** [mgechev/injection-js#40]
Is there a way to dynamically resolve a bunch of dependencies without importing them into every file they need to be resolved in?

For example, I have a `WebsocketCommandHandler`: 

```
export class WebsocketCommandHandler {

  private game: Game;

  public async init(emitCallback: (id, data) => void) {
    this.game = new Game();
    await this.game.init(this);
  }
```

`Game`, however, has a big constructor due to needing to initialize a lot of dependencies in a particular order:

```
export class Game {

  private ticksElapsed = 0;

  public wsCmdHandler: WebsocketCommandHandler;

  constructor(

    public logger: Logger,
    public contentManager: ContentManager,

    public db: Database,

    public accountDB: AccountDB,
    public characterDB: CharacterDB,
    public worldDB: WorldDB,

    public profanityHelper: ProfanityHelper,

    public lobbyManager: LobbyManager,
    public characterRoller: CharacterRoller,
    public itemCreator: ItemCreator,
    public npcCreator: NPCCreator,

    public calculatorHelper: CalculatorHelper,
    public itemHelper: ItemHelper,
    public npcHelper: NPCHelper,
    public characterHelper: CharacterHelper,
    public playerHelper: PlayerHelper,

    public messageHelper: MessageHelper,
    public commandHandler: CommandHandler,

    public playerManager: PlayerManager,
    public worldManager: WorldManager

  ) {}
}
```

These services also can inject each other, but this big object needs to have a reference to all of them and initialize all of them in order (that logic is elsewhere). However, I do not want to import every service in two locations (`Game` and `WebsocketCommandHandler`) just to set up the `Game` object. I would like `WebsocketCommandHandler` to be able to dynamically infer these new dependencies as they come up.

Since I believe I will have to do this in `Game` (to inject all of the child services) I would like a solution to dynamic resolution so I don't need to continually update the `Game` file with the changed injection order every time I change it.

Previously I used `typescript-ioc` because it would auto inject and resolve dependencies in a particular order, but I found that it would sometimes fail to resolve things and give unhelpful output so tracking down the errors are nigh impossible and this particular solution seems a bit cleaner.

The closest thing I found is #6, but this even still seems to have a fair bit of manual work associated per service.

**Comment by jorroll** [comment]
I imagine the easiest way would be if all the constructor services were registered with the DI system, and the `Game` class was also registered with the DI system. This way you could use the DI system to create a `Game` instance.

Something like

```ts
@Injectable()
export class Game {

  private ticksElapsed = 0;

  public wsCmdHandler: WebsocketCommandHandler;

  constructor(
    public logger: Logger,
    public contentManager: ContentManager,

    public db: Database,

    public accountDB: AccountDB,
    public characterDB: CharacterDB,
    public worldDB: WorldDB,

    public profanityHelper: ProfanityHelper,

    public lobbyManager: LobbyManager,
    public characterRoller: CharacterRoller,
    public itemCreator: ItemCreator,
    public npcCreator: NPCCreator,

    public calculatorHelper: CalculatorHelper,
    public itemHelper: ItemHelper,
    public npcHelper: NPCHelper,
    public characterHelper: CharacterHelper,
    public playerHelper: PlayerHelper,

    public messageHelper: MessageHelper,
    public commandHandler: CommandHandler,

    public playerManager: PlayerManager,
    public worldManager: WorldManager
  ) {}
}

const injector = ReflectiveInjector.resolveAndCreate([
    Game,
    Logger,
    ContentManager,

    Database,

    AccountDB,

    // etc ...
]);

console.log(injector.get(Game) instanceof Game);
```

But I just grabbed this from the readme

**Comment by seiyria** [comment]
Yes, but then I believe I also need to go one step further and construct all of the other services, which is where I'm stuck. 

Additionally, ideally, I would like to be able to loop over the dependencies so I don't have to add them in two places (as stated).

**Comment by jorroll** [comment]
> Yes, but then I believe I also need to go one step further and construct all of the other services, which is where I'm stuck.

I'm not sure I understand. The DI system creates everything. Everything would need to be `@Injectable`.

> Additionally, ideally, I would like to be able to loop over the dependencies so I don't have to add them in two places (as stated).

Ya I didn't understand this in your OP. I imagine the "two places" are `Game` and `WebsocketCommandHandler`, except it doesn't look like `WebsocketCommandHandler` injects these dependencies. And it doesn't look like it would need to anyway, given that it has access to `Game` and game provides all the dependencies as public properties.

> Is there a way to dynamically resolve a bunch of dependencies without importing them into every file they need to be resolved in?

It sounds like your asking "is there some way for the computer to know what my dependencies are without me telling it" ?

**Comment by seiyria** [comment]
@thefliik not quite.

`WebsocketCommandHandler` will have to have an instance of `Game`, which means it will need to set up DI for all of the services going into `Game`. So, what I'm hoping to do is something like this:

```
initGame() {

	const injector = ReflectiveInjector.resolve([Game, ...Game.dependencies]); 

	// Obviously Game.dependencies doesn't exist as a property. I would like to get them dynamically, otherwise every time I add a new service to `Game`'s constructor, I also have to add it to the DI setup in `WebsocketCommandHandler`.

	const game: Game = Reflect.construct(Game, Game.dependencies.map(x => injector.get(x));

	// this would construct the Game object with this dynamic list of dependencies. However, my concern here is that I will also need to construct each of the dependencies manually. Say that I have `AccountDB` which injects `Database`. Do I also have to construct all of these dependencies before constructing `Game`?

	game.init() // would init all of the services
}
```

A simpler example might be:

* `Database` is standalone
* `AccountDB` has `Database`
* `Game` has `Database` and `AccountDB`

If I could get help setting up a simpler DI system that auto-registers dependencies with the above setup, I could probably extrapolate.

I'm having trouble setting up DI in a _convenient_ way such that if I add a dependency to the `Game` or  `AccountDB`, I have a loop that iterates over all of its dependencies and automatically creates and injects them. Otherwise, I have too many services that I would have to update manually when I want to inject a new service.

Maybe my interpretation of the documentation is what's confusing me. I just want to have a similar API to `typescript-ioc`, but with a little bit more manual control over the DI setup (`typescript-ioc` is automatic, but it fails in some cases).

I hope my explanation makes a bit more sense, but if not I'm happy to try to explain it a different way! Thanks so far.

**Comment by jorroll** [comment]
Ah, I think I understand. You're annoyed that you need to provide all the dependencies to the `ReflectiveInjector` when calling `resolveAndCreate()`.

i.e. you'd like to be able to simply

```ts
const injector = ReflectiveInjector.resolveAndCreate([Game]);
injector.get(Game)
```

rather than

```ts
const injector = ReflectiveInjector.resolveAndCreate([Game, AccountDB, Database]);
injector.get(Game);
```

Correct?

For that I don't know of anything better than building off the solution outlined in #6 

For example, [here's a function](https://stackblitz.com/edit/typescript-uzm1m6?file=index.ts) I threw together that seems to work. It recursively builds up all the dependencies of a given class.

```ts
function resolveDeps(input: new (...args: any[]) => any) {
  const deps = new Set<new (...args: any[]) => any>();

  function resolver(klass: new (...args: any[]) => any) {
    if (deps.has(klass)) return;

    deps.add(klass);
  
    ReflectiveInjector.resolve([klass])
      .reduce((a, x: ResolvedReflectiveProvider) => a.concat(x.resolvedFactories), [])
      .reduce((a, r: ResolvedReflectiveFactory) => a.concat(r.dependencies), [])
      .forEach(d => resolver(d.key.token));
  }

  resolver(input);
 
  return Array.from(deps);
}

const injector = ReflectiveInjector.resolveAndCreate(resolveDeps(Game))

console.log('result', injector.get(Game))
```

**Comment by seiyria** [comment]
Thank you! Yes, it is a bit frustrating but it seems like every DI system forces you to do it this way. `typescript-ioc` was different, but it has other, worse problems so I'm looking to move away from it. I like Angulars DI system so I figured this would be a good fit (the other libraries I've looked at look _way_ worse to set up syntactically!).

I will give this a try tomorrow and let you know if it works. If something like this did work, should it be something that's PR'd into the library? It seems valuable.

**Comment by jorroll** [comment]
Dynamically resolving dependencies in this way will not work with tree shaking / static analysis. From a static analysis point of view, it will look like none of the dependencies are used so they would be removed.

I imagine this is the reason why such a function doesn't currently exit in the library. It's use is largely limited to server applications where you don't care about bundle size (or, I suppose, by someone who knows what they are doing). You'd really need to add a special function like `ReflectiveInjector.magicResolveAndCreate(Game)` that paired with a build step / webpack plugin which did the work of dynamically resolving the dependencies (using a function like `resolveDeps()` and then transforming the `ReflectiveInjector.magicResolveAndCreate(Game)` into a call of `ReflectiveInjector.resolveAndCreate([Game, /* other deps */])` in the bundle. This would run before tree shaking and would allow the tree shaker to properly eliminate code.

All of this would be a lot more work though. It looks as if this library is basically a pure dump of the Angular DI system, with very minimal changes, so that might be another reason why there are no dynamic resolution helpers exported (Angular itself doesn't have anything like that).

**Comment by jorroll** [comment]
Even though it has limitations, I went ahead and created a PR to add this function to the library #41

**Comment by seiyria** [comment]
Alright, now I'm getting this:

```
Unhandled Rejection Error: Cannot resolve all parameters for 'Game'(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Game' is decorated with Injectable.
```

If I recall correctly, if any of my deps were specified correctly it would substitute in the name instead of using a `?`, so I think I'm missing something else yet. Some of my deps don't even have sub-dependencies so I think something else is up.

I have the function [here](https://github.com/LandOfTheRair/lotr2/blob/change-di/server/src/core/dependency-resolver.ts) - I had to change the types to `any` because the given types were throwing errors for me. 

I initialize `Game` [here](https://github.com/LandOfTheRair/lotr2/blob/change-di/server/src/helpers/core/WebsocketCommandHandler.ts#L28-L29). 

My `Game` class is [here](https://github.com/LandOfTheRair/lotr2/blob/change-di/server/src/helpers/core/Game.ts#L21-L51).

Thanks again for your help so far. This is definitely the kind of solution I'm looking for if I can get it to work!

**Comment by jorroll** [comment]
Hmm. Well I don't see anything glaringly off. The type error you ran into was probably because you have stricter type settings than stackblitz where I created the function. I don't think you can properly type the function at the moment because one of the necessary types (`ReflectiveDependency`) isn't exported.

Regarding your problem, did you see the [stackblitz link](https://stackblitz.com/edit/typescript-uzm1m6?file=index.ts) I shared with the original `resolveDeps` function? Were you able to get that example to work? Assuming the stackblitz example works as expected for you, your best bet for troubleshooting things would probably be either opening up a debugger and inspecting what *is* returned from your `resolveDeps` function (or console.logging), or expanding the stackblitz example to make it more like your code and hoping to find out what's going wrong that way.

**Comment by seiyria** [comment]
I didn't see the stackblitz link, but I do now! It looks like it works to me. I'll do a bit more debugging in that regard and see if I can come up with anything. Thanks again!

**Comment by seiyria** [comment]
@thefliik just wanted to follow up- It looks like I forgot `Injectable` on the `Game` object, and now I'm getting far more helpful errors. Thanks again for this solution and getting it into the library, this will definitely help users going forward!
