### ISSUE TITLE
How to use the makeDecorator with an object as prop

### ISSUE THREAD

**Issue by paulhobbel** [mgechev/injection-js#44]
I've been trying to create my own decorators, but don't really have any luck atm.

In angular you can do something like this:
```ts
interface ModuleDecorator {
    (module: Module): Module
    new (module: Module): Module
}

interface Module {
    providers: Provider[]
}

const Module = <ModuleDecorator>makeDecorator('Module', (module: Module) => module);
```

However when doing this with the makeDecorator provided by injection-js the properties are not set to the decorator.

After a quick search I found out this sorta works
```ts
const Module = <ModuleDecorator>makeDecorator('Module', ['module']);
```
However that creates the following
```ts
DecoratorFactory {
  module: { providers: [] }
}
```

Instead, I want the following:
```ts
DecoratorFactory {
  providers: []
}
```

**Comment by mgechev** [comment]
You can read more about TypeScript decorators here https://www.typescriptlang.org/docs/handbook/decorators.html.

`makeDecorator` is not a public function of this library.
