### ISSUE TITLE
ReflectiveInjector unable to resolve parameters of parent class

### ISSUE THREAD

**Issue by paulhobbel** [mgechev/injection-js#45]
Seems like the ReflectiveInjector is unable to resolve parameters of the parent class.
Example:
```ts
class SomeService {
  fetch() {
    console.log('fetching...');
  }
}

class abstract Parent {
  constructor(private service: SomeService) {}

  protected fetchAndDoStuff() {
    this.service.fetch();
  }
}

class Child extends Parent {
   
}
```

The injector should resolve the Parent constructor as no constructor is defined in Child. Instead it does nothing.

**Comment by mgechev** [comment]
That's the right way to go:

```ts
import { Injectable, ReflectiveInjector } from 'injection-js';
import 'reflect-metadata';

class SomeService {
  fetch() {
    console.log('fetching...');
  }
}

abstract class Parent {
  constructor(private service: SomeService) {}

  protected fetchAndDoStuff() {
    this.service.fetch();
  }
}

@Injectable()
class Child extends Parent {
  constructor(service: SomeService) {
    super(service);
  }
}

const injector = ReflectiveInjector.resolveAndCreate([
  {
    provide: SomeService,
    useClass: SomeService
  },
  {
    useClass: Child,
    provide: Child
  }
])

console.log(injector.get(Child));
```

There seems to be something off with your `Parent` class declaration. The `abstract` keyword should be before `class`. You're also missing `Injectable()` decorators.

**Comment by paulhobbel** [comment]
Oh sorry that was just a markup issue of me. Even then it fails to resolve. I mean it works if you add the constructor again, but it should work without the constructor as it should resolve the parent's constructor
