### ISSUE TITLE
How to add providers dynamically?

### ISSUE THREAD

**Issue by han4wluc** [mgechev/injection-js#47]
I have a `React` project built with `typescript` and `nextjs`.
I have modules that are loaded dynamically, so I cannot initiate them all at once, I need to initiate them dynamically.

I would like to do something like this:

```
const injector = ReflectiveInjector.resolveAndCreate([Service, Http]);

// later in the application
injector.dynamicResolveAndCreate([Service2, Http])  // Http may be found in multiple modules


injector.get(Service)
injector.get(Service2)
```

Is there currently a way to achieve this?

**Comment by mgechev** [comment]
You can pass a [parent injector](https://github.com/mgechev/injection-js/blob/dca2b5dbb0ece3a11cf0b777b8154df15f1c5d19/lib/reflective_injector.ts#L123-L126) to `createAndResolve`. This way you'll be able to dynamically overwrite some of the providers.
