### ISSUE TITLE
Class that just resolve dependencies

### ISSUE THREAD

**Issue by fauvillej** [mgechev/injection-js#6]
@mgechev Hi
Something is missing or I dont understand something... :P
I get it that we can resolve dependencies for the providers.
But I want to have a class that is not instanced in the DI but 
that resolve dependencies in its constructor...

Something like Directives in Angular 2 :

    class Service {}

    @MyElement()
    class TotoElement {
        constructor(private svc: Service) {}
    }

    const injector = ReflectiveInjector.resolveAndCreate([
        Service
    ]);

Do I have to instance `TotoElement` and resolve the constructor myself ?

Thanks

**Comment by mgechev** [comment]
```ts
class Service {}

@MyElement()
class TodoElement {
    constructor(private svc: Service) {}
}

const injector = ReflectiveInjector.resolveAndCreate([
    Service
]);
```

In this case you can do something like:

```ts
new TodoElement(injector.get(Service));
```

It'll be better to register provider for `TodoElement` as well and use the IoC provided by the `ReflectiveInjector`.

**Comment by fauvillej** [comment]
Sorry but what do you mean by IoC ?

**Comment by mgechev** [comment]
Here [it is](https://en.wikipedia.org/wiki/Inversion_of_control).

**Comment by fauvillej** [comment]
Ok so I have to implement something to make it works. It was just to be sure... Thank you

**Comment by fauvillej** [comment]
I found a solution and I post it in case someone need it :

```javascript
    class TestDep {
        log() { return 'hello'; }
    }

    @Element() // Created with makeDecorator util/decorators.ts
    class MyElement {
        constructor(private svc: TestDep) {}
        test() {
            return this.svc.log();
        }
    }

    const injector = ReflectiveInjector.resolveAndCreate([TestDep]);

    const dependencies: ReflectiveDependency[] = ReflectiveInjector.resolve([MyElement])
        .reduce((a, x: ResolvedReflectiveProvider) => a.concat(x.resolvedFactories), [])
        .reduce((a, r: ResolvedReflectiveFactory) => a.concat(r.dependencies), []);

    const deps = dependencies.map(d => d.key.token).map(t => injector.get(t));
    const element: MyElement = Reflect.construct(MyElement, deps);
    expect(element.test()).equals('hello');

**Comment by jorroll** [comment]
For anyone else running into this issue, the OP said something that was incorrect

> ...
> But I want to have a class that is not instanced in the DI but that resolve dependencies in its constructor...
> 
> Something like Directives in Angular 2 

In Angular 2, both Directives and Components are injectables and registered with the DI system. I realize they don't use the `@Injectable()` decorator, but the `@Directive()` and `@Component()` decorators also register their classes with the DI system, similar to `@Injectable()`. This is why you can inject a parent component into a child component's constructor.

I.e. this is valid in Angular

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
    <hello></hello>
  `,
})
export class AppComponent  {}

@Component({
  selector: 'hello',
  template: `
    <p> Hi </p>
  `,
})
export class HelloComponent  {
  constructor(
    private parent: AppComponent,
  ) {}
}
```

In Angular, pretty much everything uses the DI system.

If you wish to create directives replicating `@Component` and `@Decorator` from Angular, you need to create new directives which, similar to `@Injectable` from this library, register their targets with the DI system under the hood (you could probably make use of the `@Injectable` function to accomplish this). You then need to use the DI system to resolve your components/directives.

**Edit:** put another way (and as a loose analogy), in Angular `@Directive` is an extension of `@Injectable`, and `@Component` is an extension of `@Directive`. Of course, this isn't actually true (we're talking about regular functions after all), but hopefully you get the idea.
