### ISSUE TITLE
Add InjectionToken (Angular 4)

### ISSUE THREAD

**Issue by QuinntyneBrown** [mgechev/injection-js#7]
Add InjectionToken.

**Comment by mgechev** [comment]
That's a good reminder. I'll try to publish version 2 of injection-js during the weekend.

**Comment by QuinntyneBrown** [comment]
Thanks, just a placeholder issue. Appreciate it.

I want to incorporate in "custom elements v1" based apps. I think it's a good fit. Right now the my implementation is not too elegant. https://github.com/QuinntyneBrown/pagination

**Comment by mgechev** [comment]
https://github.com/mgechev/injection-js/commit/5611ab9e752ec5802bd5c1df72667d0aa4952e58 done
