### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by DxCx** [mgechev/injection-js#8]
Hi, From the readme it seems that the answer is 'no'.
but, do you have support for modules? (Similar to NgModule)

**Comment by mgechev** [comment]
No, modules are related to the context required for components and directives. They don't have direct implication for the DI of Angular.

**Comment by DxCx** [comment]
Well, i don't totally agree with you, since one (like me) might want to bind classes togather into module.. but thanks anyway, i'll just wrap the DI to implement it =)
